### PR TITLE
Fixed #29, Spawning directly vboxheadless at startvm().

### LINKED ISSUE #29: t2-vm create failure
```
$ t2-vm create
Initializing VM...
(Replacing previous VM...)
VBoxManage: error: Could not find a registered machine named 'tessel2'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(VMName).raw(), machine.asOutParam())" at line 151 of file VBoxManageMisc.cpp
Unhandled rejection Error: 1
    at Object.ensureErrorObject (/Users/rwaldron/clonez/t2-vm/node_modules/bluebird/js/main/util.js:228:20)
    at Promise._rejectCallback (/Users/rwaldron/clonez/t2-vm/node_modules/bluebird/js/main/promise.js:416:22)
    at /Users/rwaldron/clonez/t2-vm/node_modules/bluebird/js/main/promise.js:433:17
    at ChildProcess.<anonymous> (/Users/rwaldron/clonez/t2-vm/etc.js:47:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### PR DESCRIPTION
**Pull request by huseyinkozan**
Works on Ubuntu 14.04 and node 5.3.0.

### CODE REVIEW

**Comment by johnnyman727** [comment]
@huseyinkozan thanks for the contribution! Is this a fix to a particular issue or just a cleanup of the code?

File: etc.js [hunk 1]
```diff
@@ -55,7 +55,7 @@ function startvm (name) {
   return isWin ?
     spawn('vboxheadless', ['-s', name])
   :
-    spawn('sh', ['vboxheadless', '-s', name]);
+    spawn('vboxheadless', ['-s', name]);
```
Comment (kevinmehall) [inline etc.js]: Remove the isWin check since now both sides are the same?
